source: ./content
destination: ./<base-url>

baseurl: "<base-url>"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: "/:basename/"


assets:
  sources:
    - _assets/img
